spring.application.name=enajenarte
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


spring.datasource.url=jdbc:mariadb://localhost:3307/enajenarte_db
spring.datasource.username=enajenarte_user
spring.datasource.password=enajenarte_password
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a6ed29001@smtp-brevo.com
spring.mail.password=bskCWBF301rThRd
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=patricia.caamano87@gmail.com
app.contact.to=patricia.caamano87@gmail.com