spring.application.name=enajenarte
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.url=jdbc:mariadb://localhost:3307/enajenarte_db
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${MARIADB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM}
app.contact.to=${CONTACT_TO}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000